/**
 * Raw Tavily API response shapes, derived strictly from the documented
 * response fields in docs/research/providers/tavily.json (official docs:
 * https://docs.tavily.com).
 *
 * Notes from the docs:
 *  - the API is unversioned (no version segment in URLs);
 *  - `answer` is LLM-generated ("A short answer to the user's query,
 *    generated by an LLM") — synthesized content, never a primary source;
 *  - `published_date` appears on results only with topic=news, and its
 *    format is NOT documented — treat as optional and parse defensively;
 *  - errors use a consistent nested envelope: { detail: { error: string } }.
 */

/** Documented JSON error envelope: { detail: { error } }. */
export interface TavilyErrorEnvelope {
  detail: {
    error: string;
  };
}

/** One entry of `results[]` (POST /search). */
export interface TavilySearchResult {
  title: string;
  url: string;
  /** Snippet/chunk text ("a short description of the search result"). */
  content: string;
  /** Relevance score. */
  score: number;
  /** Favicon URL; present when include_favicon=true. */
  favicon?: string;
  /** Cleaned page content; present when include_raw_content is requested. */
  raw_content?: string | null;
  /** Images extracted from the source; present when include_images=true. */
  images?: unknown[];
  /**
   * Present with topic=news only ("includes published_date metadata",
   * best-practices doc). Format undocumented — parse defensively.
   */
  published_date?: string;
}

/** POST /search response. */
export interface TavilySearchResponse {
  query: string;
  /** LLM-generated answer; present when include_answer was requested. */
  answer?: string;
  /** Query-related images; empty unless include_images=true. */
  images?: unknown[];
  results: TavilySearchResult[];
  /** Present when auto_parameters=true. */
  auto_parameters?: Record<string, unknown>;
  /** Seconds taken to complete the request. */
  response_time: number;
  /** Credit usage details; present when include_usage=true. */
  usage?: Record<string, unknown>;
  request_id: string;
}
